version: '3'

services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sonarqube
    volumes:
      - $PWD/mysql-server/mysql-data:/var/lib/mysql
      - $PWD/mysql-server/mysqlconf:/etc/mysql/conf.d

  sonarqube:
    image: sopheamak/sonarqube-docker
    ports:
      - "9000:9000"
    volumes:
      - ./sonarqube-server/data/app/conf:/opt/sonarqube/conf
      - ./sonarqube-server/data/app/data:/opt/sonarqube/data
      - ./sonarqube-server/data/app/extensions:/opt/sonarqube/extensions
      - ./sonarqube-server/data/app/logs:/opt/sonarqube/logs
    environment:
      - SONARQUBE_JDBC_URL=jdbc:mysql://mysql:3306/sonarqube?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance
      - SONARQUBE_JDBC_USERNAME=root
      - SONARQUBE_JDBC_PASSWORD=root
      - DATABASE_PORT=3306
      - DATABASE_HOST=mysql
    links:
      - mysql:mysql
